version: '3'

services:
    jupytertorch:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8888:8888
        volumes:
            - ..:/data
    
